services:
  admin_server:
    build:
      context: ./admin_server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production

  facial_recognition:
    build:
      context: ./facial_recognition
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    depends_on:
      - admin_server
