services:
  admin_server:
    build:
      dockerfile: ./admin_server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production

  facial_recognition:
    build:
      dockerfile: ./facial_recognition/Dockerfile
    ports:
      - "9090:9090"
    environment:
      - FLASK_ENV=production